from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import FileResponse
import shutil
import os
import yaml
import subprocess
import glob

app = FastAPI()

UPLOAD_DIR = "data/audio"
CONFIG_PATH = "configs/inference/realtime.yaml"

os.makedirs(UPLOAD_DIR, exist_ok=True)


@app.get("/")
def health():
    return {"status": "ok"}


@app.post("/generate")
async def generate(file: UploadFile = File(...)):
    try:
        # -----------------------------
        # Save uploaded audio
        # -----------------------------
        audio_path = os.path.join(
            UPLOAD_DIR,
            file.filename
        )

        with open(audio_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        print(f"Audio saved: {audio_path}")

        # -----------------------------
        # Load realtime config
        # -----------------------------
        with open(CONFIG_PATH, "r") as f:
            config = yaml.safe_load(f)

        # Update audio path
        config["avator_1"]["audio_clips"] = {
            "audio_0": audio_path
        }

        # IMPORTANT
        config["avator_1"]["preparation"] = False

        with open(CONFIG_PATH, "w") as f:
            yaml.dump(config, f)

        print("Realtime config updated")

        # -----------------------------
        # Run MuseTalk
        # -----------------------------
        cmd = [
            "python",
            "-m",
            "scripts.realtime_inference",
            "--inference_config",
            CONFIG_PATH,
            "--result_dir",
            "results/realtime",
            "--unet_model_path",
            "models/musetalkV15/unet.pth",
            "--unet_config",
            "models/musetalkV15/musetalk.json",
            "--version",
            "v15",
            "--fps",
            "25"
        ]

        print("Starting MuseTalk inference...")

        subprocess.run(
            cmd,
            check=True
        )

        print("MuseTalk completed")

        # -----------------------------
        # Find latest generated video
        # -----------------------------
        videos = glob.glob(
            "results/v15/avatars/avator_1/vid_output/*.mp4"
        )

        if not videos:
            raise Exception(
                "No video generated by MuseTalk"
            )

        latest_video = max(
            videos,
            key=os.path.getctime
        )

        print(f"Returning video: {latest_video}")

        # -----------------------------
        # Return video directly
        # -----------------------------
        return FileResponse(
            path=latest_video,
            media_type="video/mp4",
            filename=os.path.basename(latest_video)
        )

    except subprocess.CalledProcessError as e:
        raise HTTPException(
            status_code=500,
            detail=f"MuseTalk inference failed: {str(e)}"
        )

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )
